config/routes.rb
Rails.application.routes.draw do
# 会員

  #

  devise_for :users, skip: [:registrations, :passwords], controllers: {
    
    sessions: 'public/sessions'
  }

  devise_scope :user do
    
    get "users/cancel",to: "public/registrations#cancel",as:"cancel_user_registration"
    get "/users/sign_up",to: "public/registrations#new",as:"new_user_registration"
    put "/users",to: "public/registrations#update"
    post "/users",to: "public/registrations#create",as:"user_registration"
    
    patch "/users",to: "public/registrations#update"
    delete "/users",to: "public/registrations#destroy"
    
    post "guest_sign_in",to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: 'homes#top'

    get "search" => "songs#search"
    resources :songs, only: [:new,:create,:index,:show] do
      
      resources :records, only: [:new,:create,:show]
      resource :bookmarks, only: [:create,:destroy]
    end


    get 'users/check'
    patch 'users/withdraw'
    resources :users, only: [:show,:edit,:update]

  end

  # 管理者

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
     sessions: 'admin/sessions'
  }

  namespace :admin do
    
    resources :records, only: [:index]
    
    get "search" => "songs#search"
    resources :songs, only: [:index,:show,:edit,:update] do
      resources :records, only: [:show,:edit,:update,:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord

  has_many :records
  has_many :bookmarks

  validates :name, presence: true
  validates :name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :artist, presence: true, length: { maximum: 50 }
  validates :songwriter, presence: true, length: { maximum: 50 }
  validates :composer, presence: true, length: { maximum: 50 }
  validates :tie_up, length: { maximum: 50 }

  def bookmarking_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

 # ブックマーク絞り込み用
  scope :bookmarked_by, -> (user_id){joins(:bookmarks).where(bookmarks: {user_id: user_id})}

  # 検索機能

  def self.looks(colmn,ward,user,bookmark)

    if colmn == "曲名"
      songs = Song.where("name LIKE?","%#{ward}%")
    elsif colmn == "アーティスト名"
      songs = Song.where("artist LIKE?","%#{ward}%")
    elsif colmn == "作詞者名"
      songs = Song.where("songwriter LIKE?","%#{ward}%")
    elsif colmn == "作曲者名"
      songs = Song.where("composer LIKE?","%#{ward}%")
    end
    if user != 'guest_user' && 'current_admin'
      songs = songs.bookmarked_by(user.id) if bookmark == "true"
    end
    return songs
  end
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end
  
  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      flash[:notice] = "曲情報を更新しました"
      redirect_to admin_song_path(@song)
    else
      render :edit
    end
  end
  
  def search
    @colmn = params[:colmn]
    @ward = params[:ward]
    @song_looks = Song.looks(params[:colmn],params[:ward],current_admin,params[:bookmark])
    @songs = @song_looks.order(name_kana: :ASC).page(params[:page])
  end
  
  private
  
  def song_params
    params.require(:song).permit(:name,:name_kana,:artist,:songwriter,:composer,:tie_up)
  end
end

app/helpers/admin/songs_helper.rb
module Admin::SongsHelper
end

app/views/admin/songs/_song_data.html.erb
<!--曲情報-->
  <div class="row col-12 justify-content-center text-center">
    <%= link_to admin_song_path(song), class: "fs-2" do%>
      <%= song.name %>
    <% end %>
  </div>
  <div class="row col-12 justify-content-center text-center fs-3"><%= song.artist%></div>
  <div class="row col-12 justify-content-around">
    <div class="col-4">作詞：<%= song.songwriter%></div>
    <div class="col-4">作曲：<%= song.composer%></div>
  </div>
  <div class="row col-12 justify-content-center text-center">タイアップ情報</div>
  <div class="row col-12 justify-content-center text-center">
    <% if song.tie_up.present? %>
      <%= song.tie_up%>
    <% else %>
      &nbsp;
    <% end%>
  </div>

app/views/admin/songs/_song_index.html.erb
  <% if songs.exists?%>
    <div class="col-12">
      <table class="justify-content-center text-center">
        <div>
          <% if ward.present?%>
            「<%= @ward %>」
            の検索結果
          <% end %>
        </div>
        <div>
          全<%= song_looks.count %>件
        </div>
        <thead>
          <tr>
            <th class="col-2">曲名</th>
            <th class="col-2">アーティスト</th>
            <th class="col-2">作詞者</th>
            <th class="col-2">作曲者</th>
            <th class="col-3">タイアップ情報</th>
          </tr>
        </thead>
        <tbody>
          <% songs.each do |song| %>
            <tr>
              <td>
                <%= link_to admin_song_path(song) do%>
                  <%= song.name %>
                <% end %>
              </td>
              <td><%= song.artist %></td>
              <td><%= song.songwriter %></td>
              <td><%= song.composer %></td>
              <td><%= song.tie_up %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate songs, remote: true %>
    </div>
  <% else %>
    <div class="text-center">検索結果がありません</div>
  <% end %>

app/views/admin/songs/edit.html.erb
<!--メイン部分-->
  <div class="justify-content-center text-center fs-2">曲情報編集</div>
  
  <%= render 'layouts/error', obj: @song %>
  
  <%= form_with model: @song, url: admin_song_path do |f| %>
    <div class="field justify-content-center text-center">
      <%= f.label :name, "曲名"%><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", size: "25" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :name_kana, "フリガナ"%><br />
      <%= f.text_field :name_kana, autofocus: true, autocomplete: "name", size: "25" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :artist, "アーティスト名"%><br />
      <%= f.text_field :artist, autofocus: true, autocomplete: "artist", size: "25" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :songwriter, "作詞者名"%><br />
      <%= f.text_field :songwriter, autofocus: true, autocomplete: "songwriter", size: "25" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :composer, "作曲者名"%><br />
      <%= f.text_field :composer, autofocus: true, autocomplete: "composer", size: "25" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :tie_up, "タイアップ情報"%><br />
      <%= f.text_field :tie_up, autofocus: true, autocomplete: "tie_up", size: "25" %>
    </div>
    
    <div class="action justify-content-center text-center">
      <%= f.submit "編集", class: "btn btn-submit" %>
    </div>
  <% end %>

app/views/admin/songs/index.html.erb
<!--メイン部分-->


  <h1 class="justify-content-center text-center">曲一覧</h1>
  
  <!--検索フォーム-->
  <%= form_with url: admin_search_path(@songs), method: :get, local: false do|f| %>
      <div class="field justify-content-center text-center">
        <%= f.text_field :ward %>
        <%= f.select :colmn, options_for_select([['曲名'], ['アーティスト名'], ['作詞者名'], ['作曲者名']]) %>
      </div>
      <div class="row justify-content-around">
        <div class="text-center">
          <%= f.submit "曲を検索", class: "btn btn-submit"%>
        </div>
        <!--%= link_to new_song_path, class: "btn btn-primary" do%>-->
        <!--  <div>新曲登録</div>-->
        <!--% end %>-->
      </div>
  <% end %>


  <!--曲一覧-->
  <div id="search"></div>

app/views/admin/songs/search.js.erb
<!--非同期通信の動作用-->
$('#search').html("<%= escape_javascript(render partial: 'admin/songs/song_index',locals: {colmn: @colmn, ward: @ward, songs: @songs, song_looks: @song_looks}) %>");

app/views/admin/songs/show.html.erb
  <!--メイン部分-->
  <%= flash[:notice] %>
  <!--曲情報-->
  <div class="row align-items-end">
    <div class="col col-10 justify-content-center">
      <%= render 'song_data', song: @song%>
    </div>
    
    <div class="col col-2 justify-content-center">
      <%= link_to edit_admin_song_path(@song), class: "btn btn-transition" do%>
        <div>編集</div>
      <% end %>
    </div>
  </div>
  <!--記録-->