config/routes.rb
Rails.application.routes.draw do
# 会員

  #

  devise_for :users, skip: [:registrations, :passwords], controllers: {
    
    sessions: 'public/sessions'
  }

  devise_scope :user do
    
    get "users/cancel",to: "public/registrations#cancel",as:"cancel_user_registration"
    get "/users/sign_up",to: "public/registrations#new",as:"new_user_registration"
    put "/users",to: "public/registrations#update"
    post "/users",to: "public/registrations#create",as:"user_registration"
    
    patch "/users",to: "public/registrations#update"
    delete "/users",to: "public/registrations#destroy"
    
    post "guest_sign_in",to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: 'homes#top'

    get "search" => "songs#search"
    resources :songs, only: [:new,:create,:index,:show] do
      
      resources :records, only: [:new,:create,:show]
      resource :bookmarks, only: [:create,:destroy]
    end


    get 'users/check'
    patch 'users/withdraw'
    resources :users, only: [:show,:edit,:update]

  end

  # 管理者

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
     sessions: 'admin/sessions'
  }

  namespace :admin do
    
    resources :records, only: [:index]
    
    get "search" => "songs#search"
    resources :songs, only: [:index,:show,:edit,:update] do
      resources :records, only: [:show,:edit,:update,:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
  
  belongs_to :user
  belongs_to :song
  
  validates :score, presence: true , numericality: {in: 0..100.00}
  validates :share, length: { maximum: 100 }
  validates :memo, length: { maximum: 100 }
end

app/controllers/admin/records_controller.rb
class Admin::RecordsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @song = Song.all
    @all_records = Record.page(params[:all_records]).order(id: :DESC)
  end

  def show
    @record = Record.find(params[:id])
    @song = @record.song
  end

  def edit
    @record = Record.find(params[:id])
    @song = @record.song
  end
  
  def update
    @record = Record.find(params[:id])
    @song = @record.song
    if @record.update(record_params)
      flash[:notice] = "記録を編集しました"
      redirect_to admin_song_record_path(@song,@record)
    else
      render :edit
    end
  end
  
  def destroy
    record = Record.find(params[:id])
    record.destroy
    flash[:notice] = "記録を削除しました"
    redirect_to admin_records_path
  end
  
  private
  
  def record_params
    params.require(:record).permit( :user_id, :song_id, :score, :key, :share, :memo, :created_at)
  end
  
end

app/helpers/admin/records_helper.rb
module Admin::RecordsHelper
end

app/views/admin/records/_all_records.html.erb
  <div class="col-12">
    <table class=" col-12 text-center">
      <thead>
        <th class="col-3">会員名</th>
        <th class="col-4">曲名</th>
        <th class="col-3">記録日時</th>
        <th class="col-2">点数</th>
      </thead>
      <tbody>
        <% records.each do |record| %>
          <tr>
            <td><%= record.user.name %></td>
            <td><%= record.song.name %></td>
            <td>
              <%= link_to admin_song_record_path(@song,record) do%>
              <%= record.created_at.strftime("%y/%m/%d %H:%M") %>
              <% end %>
            </td>
            <td><%= number_with_precision(record.score, precision: 2) %></td>
          </tr>
        <% end %>
      </tbody>
      
    </table>
    <%= paginate @all_records, :param_name => 'all_records', remote: true %>
  </div>

app/views/admin/records/_user_records.html.erb
  <div class="col-12">
    <table class="col-12 text-center">
      <thead>
        <th class="col-4">曲名</th>
        <th class="col-3">記録日時</th>
        <th class="col-3">点数</th>
        <th class="col-2">キー</th>
      </thead>
      <tbody>
        <% records.each do |record| %>
          <tr>
            <td><%= record.song.name %></td>
            <td>
              <%= link_to admin_song_record_path(@song,record) do%>
              <%= record.created_at.strftime("%y/%m/%d %H:%M") %>
              <% end %>
              </td>
            <td><%= number_with_precision(record.score, precision: 2) %></td>
            <td><%= record.key %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @user_records, :param_name => 'user_records', remote: true %>
  </div>

app/views/admin/records/edit.html.erb
<!--メイン部分-->
  <!--曲情報-->
  <div class="row col-12">
    <%= render 'admin/songs/song_data', song: @song %>
  </div>
  
  

  <!--記録フォーム-->
  <div class="justify-content-center text-center fs-2">記録編集</div>

  <%= render 'layouts/error', obj: @record %>

  <%= form_with model: @record, url: admin_song_record_path do |f| %>
    <%= f.hidden_field :song_id => @song.id %>
    <div class="field justify-content-center text-center">
      <%= f.label :score, "点数" %><br />
      <%= f.number_field :score, step: "0.01", in: 0.00..100.00, autofocus: true, autocomplete: "score" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :key, "キー"%><br />
      <%= f.select :key, ["-12", "-11", "-10","-9","-8","-7","-6","-5","-4","-3","-2","-1","±0", "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9", "+10", "+11", "+12"], { include_blank: "" }, autocomplete: "key" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :share, "共有する事"%><br />
      <%= f.text_area :share, autofocus: true, autocomplete: "share", size: "25x4" %>
    </div>
    <div class="field justify-content-center text-center">
      <%= f.label :memo, "共有されないメモ"%><br />
      <%= f.text_area :memo, autofocus: true, autocomplete: "memo", size: "25x4" %>
    </div>
  
    <div class="action justify-content-center text-center ">
      <%= f.submit '記録する', class:"btn btn-submit"%>
    </div>
  <% end %>

app/views/admin/records/index.html.erb
  <%= flash[:notice] %>
  <h1 class="">記録一覧</h1>
  <div class="col-12" id="show_all_records">
    <%= render 'admin/records/all_records', records: @all_records%>
  </div>

app/views/admin/records/index.js.erb
<!--非同期通信の動作用-->
$('#show_all_records').html("<%= escape_javascript(render 'admin/records/all_records', records: @all_records) %>");

app/views/admin/records/show.html.erb
<!--メイン部分-->
  <!--曲情報-->
  <%= flash[:notice] %>
  <div class="row align-items-end">
    <div class="col col-10 justify-content-center">
      <%= render 'admin/songs/song_data', song: @song %>
    </div>
    
    <div class="col col-2 justify-content-center">
      <div>
        <%= link_to edit_admin_song_record_path(@record), class: "btn btn-transition justify-content-center" do%>
          <div>編集</div>
        <% end %>
      </div>
      
      <div>
        <%= link_to admin_song_record_path(@record), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-caution justify-content-center" do%>
          <div>削除</div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="row col-12 fs-2">記録詳細</div>
  <table class="col-12">
    <tr>
      <th class="col-3 text-center">記録者</th>
      <td class="col-9 text-center">
        <%= link_to admin_user_path(@record.user_id) do %>
            <%= @record.user.name %>
          <% end %>
      </td>
    </tr>
    <tr>
      <th class="col-3 text-center">記録日時</th>
      <td class="col-9 text-center"><%= @record.created_at.strftime("%y/%m/%d %H:%M") %></td>
    </tr>
    <tr>
      <th class="col-3 text-center">点数</th>
      <td class="col-9 text-center"><%= number_with_precision(@record.score, precision: 2) %></td>
    </tr>
    <tr>
      <th class="col-3 text-center">キー</th>
      <td class="col-9 text-center"><%= @record.key %></td>
    </tr>
    <tr>
      <th class="col-3 text-center">共有する事</th>
      <td class="col-9"><%= @record.share %></td>
    </tr>
    <tr>
      <th class="col-3 text-center">共有しないメモ</th>
      <td class="col-9"><%= @record.memo %></td>
    </tr>
  </table>