config/routes.rb
Rails.application.routes.draw do
# 会員

  #

  devise_for :users, skip: [:registrations, :passwords], controllers: {
    
    sessions: 'public/sessions'
  }

  devise_scope :user do
    
    get "users/cancel",to: "public/registrations#cancel",as:"cancel_user_registration"
    get "/users/sign_up",to: "public/registrations#new",as:"new_user_registration"
    put "/users",to: "public/registrations#update"
    post "/users",to: "public/registrations#create",as:"user_registration"
    
    patch "/users",to: "public/registrations#update"
    delete "/users",to: "public/registrations#destroy"
    
    post "guest_sign_in",to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: 'homes#top'

    get "search" => "songs#search"
    resources :songs, only: [:new,:create,:index,:show] do
      
      resources :records, only: [:new,:create,:show]
      resource :bookmarks, only: [:create,:destroy]
    end


    get 'users/check'
    patch 'users/withdraw'
    resources :users, only: [:show,:edit,:update]

  end

  # 管理者

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
     sessions: 'admin/sessions'
  }

  namespace :admin do
    
    resources :records, only: [:index]
    
    get "search" => "songs#search"
    resources :songs, only: [:index,:show,:edit,:update] do
      resources :records, only: [:show,:edit,:update,:destroy]
    end

    resources :users, only: [:index,:show,:edit,:update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_all_records.html.erb
  <table class="table text-light text-center">
    <thead>
      <th>会員名</th>
      <th>曲名</th>
      <th>記録日時</th>
      <th>点数</th>
      <th>キー</th>
      <th></th>
    </thead>
    <tbody>
      <% records.each do |record| %>
        <tr>
          <td><%= record.user.name %></td>
          <td><%= record.song.name %></td>
          <td>
            <%= link_to song_record_path(@song,record) do%>
            <%= record.created_at %>
            <% end %>
          </td>
          <td><%= number_with_precision(record.score, precision: 2) %></td>
          <td><%= record.key %></td>
        </tr>
      <% end %>
    </tbody>
    
  </table>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
    <div>
      <h3>入力項目が不足しています</h3>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_line_graph.html.erb
  <div class="w-100">
  <!--graph-area">-->
    <div class="w-100" style="position: relative; height: 50vw; width: 100%; padding-right: 45px;">
      <canvas id="myLineChart"></canvas>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      Chart.defaults.font.size = 16;
      let ctx = document.getElementById("myLineChart");
      let myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: [
            "前回","2回前","3回前","4回前","5回前","6回前","7回前","8回前","9回前","10回前","11回前","12回前","13回前","14回前","15回前","16回前","17回前","18回前","19回前","20回前","21回前","22回前","23回前","24回前","25回前",
          ],
          datasets: [
            {
              label: '点数',    //系列名
              data: [    //x軸データ
                <% @user_graph.each do |graph|%>
                  <%= graph.score %>,
                <% end %>
              ],
              borderColor: "#5cb6e4",    //線の色
              tension: 0.2,    //線の曲線度合い
            },
          ]
        },
        options: {
          plugins: {
            title: {    //グラフタイトル
              display: true,    //表示するか否か
              font: {size: '18'},
              text: '直近25回の点数',    //文面
            },
          },
          responsive: true,    //画面サイズ変更に伴ってグラフのサイズ変更するか否か
          maintainAspectRatio: false,    //グラフサイズの縦横比固定
          backgroundColor: "#050B0D",    //背景色
          scales: {    //軸に対する設定
            y:{    //y軸に対する設定
              min: 0,    //y軸の最小値
              max: 100.00,    //y軸の最大値
            },
            x:{    //x軸に対する設定
              reverse: true,
              display: false,
            },
          },
        }
      });
    </script>
  </div>

app/views/layouts/_sidebar.html.erb
<div class="col-12">
<!--サイト名-->
  <div class="text-center fs-3">
    歌うたいの</br>修練場
  </div>

<!--会員-->
  <% if user_signed_in? %>
    <!--曲一覧-->
    <%= link_to songs_path do %>
      <div class="border-top text-center py-2">曲一覧</div>
    <% end %>

    <!--マイページ-->
    <% unless current_user.guest_user? %>
      <div >
        <%= link_to user_path(current_user), data: {"turbolinks" => false} do %>
        <div class="border-top text-center py-2">マイぺージ</div>
        <% end %>
      </div>
    <% end %>

    <!--ログアウト-->
    <div>
      <%= link_to  destroy_user_session_path, method: :delete do %>
      <div class="border-top text-center py-2">Log out</div>
      <% end %>
    </div>

  <!--管理者-->
  <% elsif admin_signed_in? %>

    <!--記録一覧-->
    <div>
      <%= link_to  admin_records_path, method: :get do %>
      <div class="border-top text-center py-2">記録一覧</div>
      <% end %>
    </div>


    <!--曲一覧-->
    <div>
      <%= link_to  admin_songs_path, method: :get do %>
      <div class="border-top text-center py-2">曲一覧</div>
      <% end %>
    </div>

    <!--会員一覧-->
    <div>
      <%= link_to admin_users_path(current_user) do %>
      <div class="border-top text-center py-2">修練者一覧</div>
      <% end %>
    </div>

    <!--ログアウト-->
    <div>
      <%= link_to destroy_admin_session_path, method: :delete do %>
      <div class="border-top text-center py-2">Log out</div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<htm lang="ja">
  <head>
    <title>Utautainosyuurennjou</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">-->
  </head>

  <body>
    <header class="header-container">
      
    </header>
    <main class="main-container">
      <div class="row h-auto">
        <% if signed_in? %>
          <div class="col col-md-3 col-sm-3 col-3 sidebar">
            <div class="sidebar_fixed">
              <%= render 'layouts/sidebar'%>
            </div>
          </div>
          <div class="col col-md-9 col-sm-9 col-9">
            <%= yield %>
          </div>
        <% else %>
          <div class="col col-md-12 col-sm-12 col-xs-12">
            <%= yield %>
          </div>
        <% end %>
        
      </div>
    </main>
    <footer></footer>
  </body>
</html>